const id = (n: number) =>
  `018f0000-0000-7000-8000-${String(n).padStart(12, "0")}`;
const time = "2026-09-21T12:00:00Z";
export function restartProposal() {
  return {
    id: id(1),
    generation_id: id(2),
    fingerprint: "a".repeat(64),
    action: {
      action: "agent_run.start",
      task_id: id(3),
      expected_version: 9,
      changes: {
        provider_id: id(4),
        expected_provider_version: 2,
        expected_provider_config_version: 3,
        restart_of_run_id: id(5),
      },
    },
    preview: {
      label: "当前任务",
      before: {},
      after: {},
      agent_run_start: {
        task: {
          id: id(3),
          title: "当前任务",
          description: "当前说明",
          completion_criteria: "检查数据",
          status: "in_progress",
          kind: "work",
          review_policy: "manual",
          priority: "P1",
          project_id: null,
          parent_task_id: null,
          due_date: null,
          planned_date: null,
          estimated_minutes: null,
          actual_minutes: 0,
          manual_order: null,
          version: 9,
          created_at: time,
          updated_at: time,
        },
        assignment: {
          id: id(6),
          role: "assignee",
          assigned_at: time,
          actor_id: id(7),
        },
        agent: {
          id: id(7),
          display_name: "Agent",
          type: "agent",
          status: "active",
          version: 1,
        },
        adapter: {
          id: id(8),
          display_name: "执行器",
          kind: "builtin",
          protocol_version: "opc-agent-pipe-v1",
          status: "enabled",
          health_status: "healthy",
          isolation_status: "verified",
          execution_ready: true,
          version: 1,
        },
        provider: {
          id: id(4),
          name: "当前模型",
          kind: "remote",
          protocol: "openai_chat",
          model: "current",
          status: "ready",
          health_status: "healthy",
          version: 2,
          config_version: 3,
          leaves_device: true,
        },
        attempt: 1,
        execution_contract_version: 1,
        runtime_limits: { timeout_seconds: 600, max_result_bytes: 65536 },
        success_does_not_complete_task: true,
        result_requires_manual_review: true,
        restart: {
          run_id: id(5),
          task_id: id(3),
          status: "succeeded",
          output_delivery_status: "retained",
          attempt: 8,
          task_version: 7,
          actor_id: id(9),
          provider_id: id(10),
          model: "old",
          completed_at: time,
        },
      },
    },
    status: "pending",
    can_confirm: true,
    result_id: null,
    result_version: null,
    route: `/tasks/${id(3)}?agent_run=${id(5)}`,
    created_at: time,
    decided_at: null,
  };
}
