import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
  linkSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, basename, resolve } from "node:path";
import {
  buildOptions,
  boundEnvironment,
  helperDigestKey,
  stageHelper,
  stageImage,
} from "./build-desktop.mjs";
import {
  bindingPublicKeyEnv,
  bindingFileName,
  createBuildSigner,
  stageBuildBinding,
  verifyBuildBinding,
} from "./desktop-build-binding.mjs";

test("staging replaces its entry without modifying existing hardlink aliases", () => {
  const dir = mkdtempSync(join(tmpdir(), "opc-helper-build-test-"));
  try {
    const source = join(dir, "built.exe");
    const old = join(dir, "retained.exe");
    const target = join(
      dir,
      "opc-file-security-helper-x86_64-pc-windows-msvc.exe",
    );
    writeFileSync(source, "new artifact, not executed");
    writeFileSync(old, "retained bytes");
    linkSync(old, target);
    assert.equal(
      stageHelper(source, dir, "x86_64-pc-windows-msvc"),
      createHash("sha256").update(readFileSync(source)).digest("hex"),
    );
    assert.equal(readFileSync(old, "utf8"), "retained bytes");
    assert.equal(readFileSync(target, "utf8"), "new artifact, not executed");
    assert.equal(
      readdirSync(dir).some((p) => p.startsWith(".opc-helper-stage-")),
      false,
    );
    assert.throws(() => stageHelper(source, dir, "../escape"));
  } finally {
    assert.equal(dirname(resolve(dir)), resolve(tmpdir()));
    assert.ok(basename(dir).startsWith("opc-helper-build-test-"));
    rmSync(dir, { recursive: true });
  }
});

test("build policy is native only and rejects unbound configuration overrides", () => {
  assert.deepEqual(buildOptions(["--debug", "--no-bundle"], "win32"), {
    withHelper: true,
    profile: "debug",
    args: ["--debug", "--no-bundle"],
  });
  assert.equal(buildOptions([], "linux").withHelper, false);
  for (const args of [
    ["--config", "untrusted"],
    ["--target", "other"],
    ["--runner", "other"],
    ["--debug", "--debug"],
    ["--features", "skip-check"],
  ])
    assert.throws(() => buildOptions(args, "win32"));
});
test("digest is generated by this build, never inherited from ambient settings", () => {
  const original = {
    OTHER: "retained",
    [helperDigestKey]: "stale",
    [bindingPublicKeyEnv]: "untrusted",
  };
  assert.deepEqual(boundEnvironment(original, null), { OTHER: "retained" });
  const digest = "ab".repeat(32);
  assert.equal(boundEnvironment(original, digest)[helperDigestKey], digest);
  assert.equal(original[helperDigestKey], "stale");
  for (const invalid of ["", "AB".repeat(32), "a".repeat(63), "0".repeat(65)])
    assert.throws(() => boundEnvironment(original, invalid));
});

test("ephemeral build signer binds exactly one pair and rejects substitutions", () => {
  const signer = createBuildSigner();
  const other = createBuildSigner();
  assert.match(signer.publicHex, /^[0-9a-f]{128}$/);
  assert.deepEqual(Object.keys(signer).sort(), ["publicHex", "signPair"]);
  const manifest = signer.signPair("ab".repeat(32), "cd".repeat(32));
  assert.equal(verifyBuildBinding(manifest, signer.publicHex), true);
  assert.equal(verifyBuildBinding(manifest, other.publicHex), false);
  for (const altered of [
    { ...manifest, helperSha256: "ef".repeat(32) },
    { ...manifest, desktopSha256: "ef".repeat(32) },
    { ...manifest, signature: "00".repeat(64) },
    { ...manifest, version: 2 },
    { ...manifest, approved: true },
  ])
    assert.equal(verifyBuildBinding(altered, signer.publicHex), false);
  assert.throws(() => signer.signPair("ab".repeat(32), "cd".repeat(32)));
  const failed = createBuildSigner();
  assert.throws(() => failed.signPair("bad", "cd".repeat(32)));
  assert.throws(() => failed.signPair("ab".repeat(32), "cd".repeat(32)));
});

test("public CNG interoperability vector verifies without a stored private key", () => {
  const fixture = JSON.parse(
    readFileSync(
      new URL(
        "../apps/desktop/src-tauri/src/file_security_helper/build_binding_fixture.json",
        import.meta.url,
      ),
    ),
  );
  assert.equal(verifyBuildBinding(fixture.manifest, fixture.publicKey), true);
});

test("signed manifest staging preserves existing aliases and has no secret fields", () => {
  const dir = mkdtempSync(join(tmpdir(), "opc-helper-build-test-"));
  try {
    const retained = join(dir, "retained");
    const destination = join(dir, bindingFileName);
    writeFileSync(retained, "keep these bytes");
    linkSync(retained, destination);
    const signer = createBuildSigner();
    const manifest = signer.signPair("ab".repeat(32), "cd".repeat(32));
    stageBuildBinding(destination, manifest, signer.publicHex);
    assert.equal(readFileSync(retained, "utf8"), "keep these bytes");
    assert.deepEqual(JSON.parse(readFileSync(destination)), manifest);
    assert.deepEqual(Object.keys(manifest).sort(), [
      "desktopSha256",
      "helperSha256",
      "signature",
      "version",
    ]);
    assert.equal(
      readdirSync(dir).some((name) => name.startsWith(".opc-binding-stage-")),
      false,
    );
    assert.throws(() =>
      stageBuildBinding(
        destination,
        { ...manifest, version: 2 },
        signer.publicHex,
      ),
    );
    assert.deepEqual(JSON.parse(readFileSync(destination)), manifest);
  } finally {
    assert.equal(dirname(resolve(dir)), resolve(tmpdir()));
    assert.ok(basename(dir).startsWith("opc-helper-build-test-"));
    rmSync(dir, { recursive: true });
  }
});

test("desktop deliverable is detached from Cargo cache aliases before signing", () => {
  const dir = mkdtempSync(join(tmpdir(), "opc-helper-build-test-"));
  try {
    const cache = join(dir, "cached.exe");
    const deliverable = join(dir, "desktop.exe");
    writeFileSync(cache, "original build bytes");
    linkSync(cache, deliverable);
    stageImage(deliverable, deliverable);
    assert.equal(readFileSync(cache, "utf8"), "original build bytes");
    writeFileSync(cache, "next compilation");
    assert.equal(readFileSync(deliverable, "utf8"), "original build bytes");
    assert.equal(
      readdirSync(dir).some((p) => p.startsWith(".opc-helper-stage-")),
      false,
    );
  } finally {
    assert.equal(dirname(resolve(dir)), resolve(tmpdir()));
    assert.ok(basename(dir).startsWith("opc-helper-build-test-"));
    rmSync(dir, { recursive: true });
  }
});
