import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Plus } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { useCreateContentItem, useProjectsQuery, useContentItemsQuery } from "../api/hooks";
import { EmptyState, ErrorState, SkeletonRows } from "../components/feedback";
import { Modal } from "../components/Modal";
import { PageHeader } from "../components/PageHeader";
import type { ContentItemStatus } from "../types/models";

const statusLabel: Record<ContentItemStatus, string> = { draft: "草稿", in_review: "待审核", scheduled: "已排期", published: "已发布", cancelled: "已取消", archived: "已归档" };
const statusClass: Record<ContentItemStatus, string> = { draft: "status-neutral", in_review: "status-purple", scheduled: "status-blue", published: "status-green", cancelled: "status-red", archived: "status-neutral" };
function rangeForMonth(month: Date) { const from = new Date(month.getFullYear(), month.getMonth(), 1); const to = new Date(month.getFullYear(), month.getMonth() + 1, 1); return { from: from.toISOString(), to: to.toISOString() }; }
function displaySchedule(value: string | null) { return value ? new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "未排期"; }

function CreateContentItemModal({ open, onClose, month }: { open: boolean; onClose: () => void; month: Date }) {
  const create = useCreateContentItem(); const projects = useProjectsQuery({ page: 1, pageSize: 100, sort: "name" }, open);
  const [title, setTitle] = useState(""); const [platform, setPlatform] = useState(""); const [projectId, setProjectId] = useState(""); const [date, setDate] = useState(""); const [error, setError] = useState<string | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!title.trim() || !platform.trim()) { setError("请填写内容标题和平台。"); return; } const scheduledAt = date ? new Date(`${date}T09:00:00`).toISOString() : null; create.mutate({ title: title.trim(), platform: platform.trim(), projectId: projectId || null, scheduledAt, scheduledTimezone: scheduledAt ? Intl.DateTimeFormat().resolvedOptions().timeZone : null }, { onSuccess: () => { setTitle(""); setPlatform(""); setProjectId(""); setDate(""); onClose(); } }); };
  return <Modal footer={<><button className="button button-secondary" disabled={create.isPending} onClick={onClose} type="button">取消</button><button className="button button-primary" disabled={create.isPending} form="content-item-form" type="submit">{create.isPending ? "正在创建…" : "创建内容"}</button></>} onClose={onClose} open={open} title={`新建 ${month.getFullYear()}年${month.getMonth() + 1}月内容`} width="560px"><form id="content-item-form" onSubmit={submit}><label className="form-field"><span>内容标题</span><input autoFocus maxLength={200} onChange={(e) => setTitle(e.target.value)} placeholder="例如：发布本周产品更新" value={title} /></label><label className="form-field"><span>发布平台</span><input maxLength={64} onChange={(e) => setPlatform(e.target.value)} placeholder="例如：微信公众号" value={platform} /></label><label className="form-field"><span>计划日期（可选）</span><input onChange={(e) => setDate(e.target.value)} type="date" value={date} /></label><label className="form-field form-field-last"><span>关联项目（可选）</span><select onChange={(e) => setProjectId(e.target.value)} value={projectId}><option value="">不关联项目</option>{projects.data?.items.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>{error || create.isError ? <p className="form-field-error">{error ?? "创建失败，请检查本地服务后重试。"}</p> : null}</form></Modal>;
}

export function ContentCalendarPage() {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [creating, setCreating] = useState(false); const [status, setStatus] = useState<ContentItemStatus | "">("");
  const range = useMemo(() => rangeForMonth(month), [month]); const query = useContentItemsQuery({ scheduledFrom: range.from, scheduledTo: range.to, status: status || undefined, includeArchived: status === "archived" }); const items = query.data?.items ?? [];
  const shift = (offset: number) => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + offset, 1));
  return <div className="page"><PageHeader actions={<button className="button button-primary" onClick={() => setCreating(true)} type="button"><Plus size={15} />新建内容</button>} meta={<span className="page-count">{query.isPending ? "读取中" : query.isSuccess ? `${query.data.meta.total} 条` : "数据不可用"}</span>} title="内容日历" /><div className="toolbar content-calendar-toolbar"><button aria-label="上个月" className="button button-secondary button-icon" onClick={() => shift(-1)} type="button"><ChevronLeft size={16} /></button><strong className="content-calendar-month">{month.getFullYear()} 年 {month.getMonth() + 1} 月</strong><button aria-label="下个月" className="button button-secondary button-icon" onClick={() => shift(1)} type="button"><ChevronRight size={16} /></button><label className="toolbar-select"><span className="sr-only">状态</span><select onChange={(e) => setStatus(e.target.value as ContentItemStatus | "")} value={status}><option value="">未归档</option>{Object.entries(statusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>{query.isError ? <ErrorState message="无法读取内容日历，请确认本地服务已连接。" onRetry={() => void query.refetch()} /> : null}{query.isPending ? <SkeletonRows count={4} /> : null}{query.isSuccess && items.length === 0 ? <EmptyState action={<button className="button button-primary" onClick={() => setCreating(true)} type="button"><Plus size={15} />新建第一条内容</button>} message="内容排期保存在本机，不会连接或发布到外部平台。" title="本月暂无内容排期" /> : null}{items.length > 0 ? <section className="content-calendar-list" aria-label="本月内容排期">{items.map((item) => <article className="content-calendar-card" key={item.id}><div className="content-calendar-card-main"><span className={`status-badge ${statusClass[item.status]}`}>{statusLabel[item.status]}</span><h2>{item.title}</h2><p>{item.platform}</p></div><div className="content-calendar-card-meta"><span><Clock3 size={14} />{displaySchedule(item.scheduledAt)}</span><span>{item.requiredTaskDone}/{item.requiredTaskTotal} 项准备任务</span></div></article>)}</section> : null}<CreateContentItemModal month={month} onClose={() => setCreating(false)} open={creating} /></div>;
}
