import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Edit3, Plus, Send } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { useCreateContentItem, useProjectsQuery, useContentItemsQuery, usePublishContentItem, useScheduleContentItem, useUpdateContentItem } from "../api/hooks";
import { EmptyState, ErrorState, SkeletonRows } from "../components/feedback";
import { Modal } from "../components/Modal";
import { PageHeader } from "../components/PageHeader";
import type { ContentItem, ContentItemStatus } from "../types/models";

const statusLabel: Record<ContentItemStatus, string> = { draft: "草稿", in_review: "待审核", scheduled: "已排期", published: "已发布", cancelled: "已取消", archived: "已归档" };
const statusClass: Record<ContentItemStatus, string> = { draft: "status-neutral", in_review: "status-purple", scheduled: "status-blue", published: "status-green", cancelled: "status-red", archived: "status-neutral" };
const editableStatuses: Array<Exclude<ContentItemStatus, "published">> = ["draft", "in_review", "scheduled", "cancelled", "archived"];

function rangeForMonth(month: Date) {
  return { from: new Date(month.getFullYear(), month.getMonth(), 1).toISOString(), to: new Date(month.getFullYear(), month.getMonth() + 1, 1).toISOString() };
}
function displaySchedule(value: string | null) { return value ? new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "未排期"; }
function localDateTime(value: string | null) { if (!value) return ""; const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function mutationMessage(error: unknown) { return error instanceof Error && error.message ? error.message : "操作失败，请刷新后重试。"; }

function CreateContentItemModal({ open, onClose, month }: { open: boolean; onClose: () => void; month: Date }) {
  const create = useCreateContentItem();
  const projects = useProjectsQuery({ page: 1, pageSize: 100, sort: "name" }, open);
  const [title, setTitle] = useState(""); const [platform, setPlatform] = useState(""); const [projectId, setProjectId] = useState(""); const [date, setDate] = useState(""); const [error, setError] = useState<string | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!title.trim() || !platform.trim() || !date) { setError("请填写内容标题、平台和计划日期。"); return; }
    const scheduledAt = new Date(`${date}T09:00:00`).toISOString();
    create.mutate({ title: title.trim(), platform: platform.trim(), status: "scheduled", projectId: projectId || null, scheduledAt, scheduledTimezone: Intl.DateTimeFormat().resolvedOptions().timeZone }, { onSuccess: () => { setTitle(""); setPlatform(""); setProjectId(""); setDate(""); onClose(); } });
  };
  return <Modal footer={<><button className="button button-secondary" disabled={create.isPending} onClick={onClose} type="button">取消</button><button className="button button-primary" disabled={create.isPending} form="content-item-form" type="submit">{create.isPending ? "正在创建…" : "创建内容"}</button></>} onClose={onClose} open={open} title={`新建 ${month.getFullYear()}年${month.getMonth() + 1}月内容`} width="560px"><form id="content-item-form" onSubmit={submit}><label className="form-field"><span>内容标题</span><input autoFocus maxLength={200} onChange={(event) => setTitle(event.target.value)} placeholder="例如：发布本周产品更新" value={title} /></label><label className="form-field"><span>发布平台</span><input maxLength={64} onChange={(event) => setPlatform(event.target.value)} placeholder="例如：微信公众号" value={platform} /></label><label className="form-field"><span>计划日期</span><input onChange={(event) => setDate(event.target.value)} required type="date" value={date} /></label><label className="form-field form-field-last"><span>关联项目（可选）</span><select onChange={(event) => setProjectId(event.target.value)} value={projectId}><option value="">不关联项目</option>{projects.data?.items.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>{error || create.isError ? <p className="form-field-error">{error ?? mutationMessage(create.error)}</p> : null}</form></Modal>;
}

function EditContentItemModal({ item, onClose }: { item: ContentItem | null; onClose: () => void }) {
  const update = useUpdateContentItem(); const schedule = useScheduleContentItem(); const publish = usePublishContentItem();
  const projects = useProjectsQuery({ page: 1, pageSize: 100, sort: "name" }, Boolean(item));
  const [title, setTitle] = useState(item?.title ?? ""); const [platform, setPlatform] = useState(item?.platform ?? ""); const [projectId, setProjectId] = useState(item?.projectId ?? ""); const [notes, setNotes] = useState(item?.notes ?? ""); const [status, setStatus] = useState<Exclude<ContentItemStatus, "published">>((item?.status === "published" ? "draft" : item?.status) ?? "draft"); const [scheduledAt, setScheduledAt] = useState(localDateTime(item?.scheduledAt ?? null)); const [externalLink, setExternalLink] = useState(item?.externalLink ?? "");
  if (!item) return null;
  const busy = update.isPending || schedule.isPending || publish.isPending;
  const saveDetails = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); update.mutate({ id: item.id, input: { title: title.trim(), platform: platform.trim(), projectId: projectId || null, notes: notes.trim() || null, status, expectedVersion: item.version } }, { onSuccess: onClose }); };
  const saveSchedule = () => { const value = scheduledAt ? new Date(scheduledAt).toISOString() : null; schedule.mutate({ id: item.id, input: { scheduledAt: value, scheduledTimezone: value ? Intl.DateTimeFormat().resolvedOptions().timeZone : null, expectedVersion: item.version } }, { onSuccess: onClose }); };
  const confirmPublish = () => publish.mutate({ id: item.id, input: { externalLink: externalLink.trim() || null, expectedVersion: item.version } }, { onSuccess: onClose });
  const error = update.error ?? schedule.error ?? publish.error;
  return <Modal footer={<><button className="button button-secondary" disabled={busy} onClick={onClose} type="button">关闭</button>{item.status !== "published" && item.status !== "archived" && item.status !== "cancelled" ? <button className="button button-secondary" disabled={busy} onClick={confirmPublish} type="button"><Send size={14} />确认已发布</button> : null}<button className="button button-primary" disabled={busy || item.status === "published"} form="content-item-edit-form" type="submit">保存信息</button></>} onClose={onClose} open title="内容详情与排期" width="640px"><form id="content-item-edit-form" onSubmit={saveDetails}><div className="content-calendar-edit-grid"><label className="form-field"><span>内容标题</span><input disabled={item.status === "published"} maxLength={200} onChange={(event) => setTitle(event.target.value)} value={title} /></label><label className="form-field"><span>平台</span><input disabled={item.status === "published"} maxLength={64} onChange={(event) => setPlatform(event.target.value)} value={platform} /></label><label className="form-field"><span>状态</span><select disabled={item.status === "published"} onChange={(event) => setStatus(event.target.value as Exclude<ContentItemStatus, "published">)} value={status}>{editableStatuses.map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></label><label className="form-field"><span>关联项目</span><select disabled={item.status === "published"} onChange={(event) => setProjectId(event.target.value)} value={projectId}><option value="">不关联项目</option>{projects.data?.items.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="form-field content-calendar-edit-wide"><span>备注</span><textarea disabled={item.status === "published"} maxLength={4000} onChange={(event) => setNotes(event.target.value)} rows={3} value={notes} /></label></div><div className="content-calendar-schedule-row"><label className="form-field"><span>计划发布时间</span><input disabled={item.status === "published" || item.status === "archived"} onChange={(event) => setScheduledAt(event.target.value)} type="datetime-local" value={scheduledAt} /></label><button className="button button-secondary" disabled={busy || item.status === "published" || item.status === "archived"} onClick={saveSchedule} type="button"><CalendarDays size={14} />保存排期</button></div><label className="form-field form-field-last"><span>外部链接文本（可选，不会自动访问）</span><input maxLength={2048} onChange={(event) => setExternalLink(event.target.value)} placeholder="https://…" value={externalLink} /></label>{error ? <p className="form-field-error">{mutationMessage(error)}</p> : null}</form></Modal>;
}

export function ContentCalendarPage() {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<ContentItem | null>(null); const [status, setStatus] = useState<ContentItemStatus | "">("");
  const range = useMemo(() => rangeForMonth(month), [month]); const query = useContentItemsQuery({ scheduledFrom: range.from, scheduledTo: range.to, status: status || undefined, includeArchived: status === "archived" }); const items = query.data?.items ?? [];
  const shift = (offset: number) => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + offset, 1));
  return <div className="page"><PageHeader actions={<button className="button button-primary" onClick={() => setCreating(true)} type="button"><Plus size={15} />新建内容</button>} meta={<span className="page-count">{query.isPending ? "读取中" : query.isSuccess ? `${query.data.meta.total} 条` : "数据不可用"}</span>} title="内容日历" /><div className="toolbar content-calendar-toolbar"><button aria-label="上个月" className="button button-secondary button-icon" onClick={() => shift(-1)} type="button"><ChevronLeft size={16} /></button><strong className="content-calendar-month">{month.getFullYear()} 年 {month.getMonth() + 1} 月</strong><button aria-label="下个月" className="button button-secondary button-icon" onClick={() => shift(1)} type="button"><ChevronRight size={16} /></button><label className="toolbar-select"><span className="sr-only">状态</span><select onChange={(event) => setStatus(event.target.value as ContentItemStatus | "")} value={status}><option value="">未归档</option>{Object.entries(statusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>{query.isError ? <ErrorState message="无法读取内容日历，请确认本地服务已连接。" onRetry={() => void query.refetch()} /> : null}{query.isPending ? <SkeletonRows count={4} /> : null}{query.isSuccess && items.length === 0 ? <EmptyState action={<button className="button button-primary" onClick={() => setCreating(true)} type="button"><Plus size={15} />新建第一条内容</button>} message="内容排期保存在本机，不会连接或发布到外部平台。" title="本月暂无内容排期" /> : null}{items.length > 0 ? <section className="content-calendar-list" aria-label="本月内容排期">{items.map((item) => <article className="content-calendar-card" key={item.id}><button aria-label={`编辑 ${item.title}`} className="content-calendar-card-open" onClick={() => setEditing(item)} type="button"><div className="content-calendar-card-main"><span className={`status-badge ${statusClass[item.status]}`}>{statusLabel[item.status]}</span><h2>{item.title}</h2><p>{item.platform}</p></div><div className="content-calendar-card-meta"><span><Clock3 size={14} />{displaySchedule(item.scheduledAt)}</span><span>{item.requiredTaskDone}/{item.requiredTaskTotal} 项准备任务</span><Edit3 size={14} /></div></button></article>)}</section> : null}<CreateContentItemModal month={month} onClose={() => setCreating(false)} open={creating} />{editing ? <EditContentItemModal item={editing} key={`${editing.id}:${editing.version}`} onClose={() => setEditing(null)} /> : null}</div>;
}
